version: '3.8'

services:
  dbnode_1:
    container_name: node_1
    image: cockroachdb/cockroach:latest
    volumes:
        - ./data/node_1:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8181:8080"
    networks:
        cockroachdb_net:
          aliases:
            - node_1

  dotnet_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
         # [Choice] Update 'VARIANT' to pick a .NET Core version: 2.1, 3.1, 5.0
        VARIANT: 5.0
        # Options
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        INSTALL_AZURE_CLI: "false"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        # USER_UID: 1000
        # USER_GID: 1000
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      cockroachdb_net:
        aliases:
          - api

networks:
  cockroachdb_net:
    driver: bridge
